<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SocialApp.Core\SocialApp.Core.csproj" />
    <ProjectReference Include="..\SocialApp.Controls\SocialApp.Controls.csproj" />
    <ProjectReference Include="..\SocialApp.Images\SocialApp.Images.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>